Algoritmo "semnome"

// 4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
// entre eles.
// Ex:
// Digite um valor: 8
// Digite outro valor: 5
// A soma entre 8 e 5 é igual a 13.

Var

   n1, n2, r: inteiro

Inicio

      Escreval("Algoritmo para somar 2 números, siga as etapas.")
      Escreval("Digite o 1º número: ")
      leia(n1)
      Escreval("Digite o 2º número: ")
      leia(n2)
      
      r <- n1 + n2
      
      Escreval("A soma de ", n1," +", n2, " é = ", r,".")


Fimalgoritmo