Algoritmo "semnome"

// 15) Crie um programa que leia o número de dias trabalhados em um mês e mostre o
// salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
// por hora trabalhada.

Var

   dias, salario: real

Inicio

      Escreva("Quantos dias vocÊ trabalhou esse mês: ")
      leia(dias)
      
      Escreva()
      
      Escreval("O valor do salário será: R$", dias * 8 * 25:0:2)

Fimalgoritmo