Algoritmo "semnome"

// 7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
// sua terça parte.
// Ex:
// Digite um número: 3.5
// O dobro de 3.5 é 7.0
// A terça parte de 3.5 é 1.16666

Var

   n: real

Inicio

      Escreva("Digite um número: ")
      leia(n)
      Escreval("")
      Escreval("O dobro de ", n, " é ", n*2, ".")
      Escreval("A terça parte de ", n, " é ", n/3, ".")


Fimalgoritmo