// ArrayList<type>: SERVE PARA TIPAR O ARRAY LIST, PORQUE POR NATUREZA ELE É UMA LISTA GENÉRICA

// System.Linkq ( link: language integrated query ): APLICAR CONSULTAS EM COLEÇÕES DE DADOS
// UTILIZA O LINK PARA REALIZAR CONSULTAS EM COLEÇÕES, QUANDO UTILIZADOS JUNTO A UM FRAMEWORK 
// COMO POR EXEMPLO NO USO DE UM ORM, COMO O ELOQUENT PARA O LARAVEL, OU O ENTITY PARA O CSHARP

// 